src/payg/payg.model.ts
src/payg/payg.resolver.ts
src/payg/payg.service.ts

Refs https://github.com/subquery/network-contracts/pull/8

update payg with contract

---

src/payg/payg.model.ts
src/payg/payg.resolver.ts
src/payg/payg.service.ts

Reverts subquery/indexer-coordinator#41

Revert "update payg with contract"

---

package.json
src/db/db.module.ts
src/project/project.service.ts
src/services/docker.service.ts
src/services/network.service.ts
src/utils/contractSDK.ts
yarn.lock

- Upgrade indexer admin to fix dashboard issue for Juno Project
- Fix transaction failed issue for collecting rewards
- Support using released port for start project

Bug fix for the service

---

package.json
src/services/contract.service.ts
src/utils/template.yml

- Add new param  `store-cache-threshold` in node template this will speed up the indexing performance
- Add more debug log in contract service

Add store-cache-threshold param for node config

---

src/services/query.service.ts
src/utils/template.yml

Fix poi path issue

---

.eslintrc
dev/docker-compose.yml
package.json
src/project/project.model.ts
src/project/project.module.ts
src/project/project.resolver.ts
src/project/project.service.ts
src/services/contract.service.ts
src/services/network.service.ts
src/services/query.service.ts
src/services/types.ts
src/sync.ts
src/utils/queries.ts
yarn.lock

- Add project details to project entity
- Return project details with all required data

Get data ready for project

---

package.json
src/services/contract.service.ts

- Set gasPrice manually for withdraw assets from controller account

Fix withdraw token on Polygon

---

dev/docker-compose.yml
package.json
src/project/project.service.ts
src/services/query.service.ts
src/utils/docker.ts
src/utils/template.yml
src/yargs.ts

- Update purge POI feature, set targetHeight to `0`
- Align default configs, set all default values for Kepler Network
- Remove all the codes related with `mmrRoot file`
- Remove `volumes mount`, `-m` from template 
- Add flag `mmr-store-type=postgres`
- Remove `mmrPath` from cli config (breaking change)
- Remove mmrRoot file 
- Bump prerelease `v1.0.5-1`

Support generate mmr in Postgres

---

Dockerfile

fixes issue with docker-compose not being found.

fix dockerfile, install docker-compose another way

---

dev/docker-compose.yml
package.json
src/core/network.service.ts
src/project/project.service.ts
src/utils/docker.ts
src/utils/project.ts
src/utils/template.yml
src/yargs.ts
yarn.lock

- Don't send Tx if the network is under maintenance mode
- Don't send tx if controller is not ready

Don't try to send tx if controller is not ready

---

Dockerfile
package.json

- Fix the docker-compose in the coordinator image
- Fix the time cost issue for docker build: change `node:16` back to `node:16-alpine`

Fix Dockerfile for installing `docker-compose`

---

.gitignore
package.json
src/core/account.service.ts
src/core/contract.service.ts
src/core/network.service.ts
src/utils/contractSDK.ts

- Fix `getAliveController`
- Remove duplicate `getController` from `contract.service` to `account.service`

Fix getAlive controller

---

src/db/db.module.ts
src/project/project.service.ts
src/project/types.ts
src/utils/docker.ts
src/utils/project.ts
src/utils/template.yml

- Add `mmrStoreType` to project template

Add `mmrStoreType` to template

---

package.json
src/core/account.service.ts
src/core/contract.service.ts

Fix `missing provider` issue

---

.github/workflows/docker-dev.yml
.github/workflows/docker-prod.yml
.github/workflows/prerelease.yml
README.md
dev/docker-compose.yml
package.json
src/core/docker.registry.service.ts
src/metrics/events.ts
src/utils/project.ts

- Deploy image to `subquerynetwork` host
- Change image name to `indexer-coordinator`

Update docker hub config

---

package.json
src/core/network.service.ts
src/core/service.resolver.ts
src/migration/1688676100216-addAgentPayg.ts
src/payg/payg.resolver.ts
src/payg/payg.service.ts
src/project/project.service.ts
yarn.lock

- Upgrade `indexer-admin`
- Remove open state channel

Bug fix: db migration 

---

package.json

Reverts subquery/indexer-coordinator#135

Revert "[release] Bump v1.2.0"

---

README.md
apps/indexer-admin/TODO.md
apps/indexer-admin/package.json
apps/indexer-admin/src/hooks/paygHook.ts
apps/indexer-admin/src/hooks/projectHook.ts
apps/indexer-admin/src/pages/project-details/components/projectTabBarView.tsx
apps/indexer-admin/src/pages/project-details/config.ts
apps/indexer-admin/src/pages/project-details/payg/paygDatasource.tsx
apps/indexer-admin/src/pages/project-details/payg/paygPlans.tsx
apps/indexer-admin/src/pages/project-details/projectDetailsPage.tsx
apps/indexer-admin/src/pages/project-details/types.ts
apps/indexer-admin/src/pages/projects/projectsPage.tsx
apps/indexer-admin/src/utils/apolloClient.ts
apps/indexer-admin/src/utils/error.ts
apps/indexer-admin/src/utils/metamask.ts
apps/indexer-admin/src/utils/units.ts
apps/indexer-admin/src/utils/web3.ts
common/config/rush/pnpm-lock.yaml

feat: up-to-date admin

---

apps/indexer-coordinator/src/core/network.service.ts
apps/indexer-coordinator/src/core/query.service.ts

- Remove cron job to send `report indexing status` transaction
- Clean the codes related with report indexing status

Remove report indexing status

---

apps/indexer-admin/src/components/uptimeBar.tsx

[SQN-1715](https://onfinality.atlassian.net/browse/SQN-1715)

fix: uptime

---

README.md
apps/indexer-admin/package.json
apps/indexer-admin/src/pages/project-details/projectDetailsPage.tsx
apps/indexer-admin/src/pages/project-details/types.ts
apps/indexer-admin/src/pages/projects/components/projectItem.tsx
apps/indexer-admin/src/utils/project.ts
common/config/rush/.npmrc
common/config/rush/pnpm-lock.yaml

[SQN-1780](https://onfinality.atlassian.net/browse/SQN-1780)

feat: refine

---

apps/indexer-admin/package.json
apps/indexer-admin/src/App.tsx
apps/indexer-admin/src/components/logView.tsx
apps/indexer-admin/src/components/primary.tsx
apps/indexer-admin/src/pages/header/header.tsx
apps/indexer-admin/src/pages/project-details/components/projectStatusView.tsx
apps/indexer-admin/src/pages/projects/components/projectItem.tsx
apps/indexer-admin/src/pages/projects/styles.tsx
common/config/rush/pnpm-lock.yaml

[SQN-1724](https://onfinality.atlassian.net/browse/SQN-1724)

feat: remove react UI

---

apps/indexer-coordinator/src/payg/payg.service.ts

- Add check for channels get from db with channel ID

Add safe check for getting channel from db with id

---

apps/indexer-admin/src/pages/account/account.tsx
apps/indexer-admin/src/utils/error.ts

If unregister have something wrong, now will show the tips.
[https://onfinality.atlassian.net/browse/SQN-1883](SQN-1883)

feat: add exactly error

---

apps/indexer-admin/src/hooks/paygHook.ts
apps/indexer-coordinator/package.json
apps/indexer-coordinator/src/project/project.service.ts
apps/indexer-coordinator/src/utils/docker.ts
apps/indexer-coordinator/src/utils/template.yml
docker/dev/2_start.sh

fix template encode error
fix admin payg token error

Fix_template_and_payg

---

apps/indexer-admin/src/hooks/transactionHook.ts
apps/indexer-admin/src/pages/account/account.tsx

- Fix modal cannot close when click x.
- Fix contract log error if sdk is not ready.

fix: error handling

---

apps/indexer-proxy/utils/src/request.rs

`reqwest` start use `append`, not `replace` when has same header name.

Update request header when has authorization

---

apps/indexer-admin/src/components/forms/restartIndexing.tsx

Make an deepClone for potential change. 
`apollo/client` will return readonly data in some unknown situation.

feat(SQN-1923): deepClone project config for change

---

apps/indexer-coordinator/src/project/project.service.ts
apps/indexer-coordinator/src/utils/template.yml

and set block-confirmations to 100

disable purgeDB when db not exists

---

deploy/docker-compose.yml

As we redirect the docker-compose file  of `indexer-services` to this repo, we need to make sure the `docker-compose` is up to date.
- Update the indexer services to the latest version
- Remove `mmrPath` from coordinator service

Update docker-compose file

---

apps/indexer-admin/src/hooks/paygHook.ts
apps/indexer-admin/src/pages/project-details/payg/projectPayg.tsx

Fix the price token judgement. 
It's base on address, not token symbol.
Fix decimal when select token is USDC.

fix: decimal

---

apps/indexer-admin/src/containers/web3.tsx
apps/indexer-admin/src/pages/project-details/payg/projectPayg.tsx

Because prod version always use `build`, so need to use network to know the env.

fix: stable coin address

---

apps/indexer-admin/src/hooks/projectHook.ts
apps/indexer-admin/src/utils/queries.ts
apps/indexer-coordinator/src/core/query.service.ts
apps/indexer-coordinator/src/project/project.model.ts

update getQueryMetaData startHeight

---

apps/indexer-coordinator/src/core/query.service.ts

remove unnecessary debug log

---

apps/indexer-admin/src/components/uptimeBar.tsx

fix: uptime rate display issue

---

apps/indexer-coordinator/src/core/docker.service.ts
apps/indexer-coordinator/src/payg/payg.sync.service.ts

fix syncOpen bug

---

apps/indexer-admin/src/pages/account/account.tsx

[SQN-2032](https://onfinality.atlassian.net/browse/SQN-2032)
- Set update metadata loading to false, whatever the status of transaction.

fix(SQN-2032): update metadata loading status

---

apps/indexer-coordinator/package.json
apps/indexer-coordinator/src/core/contract.service.ts
apps/indexer-coordinator/src/core/network.service.ts
apps/indexer-coordinator/src/core/query.service.ts
apps/indexer-coordinator/src/core/types.ts
apps/indexer-coordinator/src/project/project.service.ts
apps/indexer-coordinator/src/utils/project.ts
apps/indexer-coordinator/yarn.lock

- Apply contract changes to indexer coordinator

Apply contract changes to coordinator

---

apps/indexer-admin/package.json
apps/indexer-admin/src/containers/contractSdk.tsx
apps/indexer-admin/src/hooks/projectHook.ts
apps/indexer-admin/src/hooks/transactionHook.ts
apps/indexer-admin/src/pages/project-details/components/projectStatusView.tsx
apps/indexer-admin/src/pages/project-details/config.ts
apps/indexer-admin/src/pages/project-details/projectDetailsPage.tsx
apps/indexer-admin/src/pages/project-details/types.ts
apps/indexer-admin/src/pages/projects/constant.ts
apps/indexer-admin/src/utils/error.ts
apps/indexer-admin/src/utils/indexerActions.ts
apps/indexer-admin/src/utils/project.ts
apps/indexer-admin/yarn.lock

- Apply contract changes to indexer-admin

Update contract changes for indexer admin

---

apps/indexer-proxy/proxy/Cargo.toml
apps/indexer-proxy/utils/Cargo.toml
apps/indexer-proxy/utils/src/request.rs

Add timeout to proxy request

---

apps/indexer-admin/src/hooks/projectHook.ts
apps/indexer-admin/src/pages/project-details/components/projectStatusView.tsx
apps/indexer-admin/src/pages/project-details/projectDetailsPage.tsx
apps/indexer-admin/src/pages/project-details/types.ts
apps/indexer-admin/src/pages/projects/components/projectItem.tsx
apps/indexer-admin/src/utils/queries.ts

feat: metadata

---

apps/indexer-admin/package.json
apps/indexer-admin/src/components/baseLineCharts.tsx
apps/indexer-admin/src/pages/project-details/components/projectInsights.tsx
apps/indexer-admin/src/pages/project-details/components/projectTabBarView.tsx
apps/indexer-admin/src/pages/project-details/payg/projectPayg.tsx
apps/indexer-admin/src/utils/apolloClient.ts
apps/indexer-admin/yarn.lock

[SQN-2117](https://onfinality.atlassian.net/browse/SQN-2117)

feat(SQN-2117): query statistics

---

apps/indexer-admin/package.json
apps/indexer-admin/src/App.tsx
apps/indexer-admin/src/hooks/indexerHook.ts
apps/indexer-admin/src/index.css
apps/indexer-admin/src/pages/project-details/components/projectTabBarView.tsx
apps/indexer-admin/src/pages/project-details/components/rateLimit.tsx
apps/indexer-admin/src/pages/project-details/payg/paygConfig.tsx
apps/indexer-admin/src/pages/project-details/payg/paygPlans.tsx
apps/indexer-admin/src/pages/project-details/projectDetailsPage.tsx
apps/indexer-admin/src/pages/project-details/types.ts
apps/indexer-admin/src/pages/projects/projectsPage.tsx
apps/indexer-admin/src/utils/queries.ts
apps/indexer-admin/src/utils/table.tsx
apps/indexer-admin/yarn.lock

feat: rate limit

---

apps/indexer-admin/src/containers/contractSdk.tsx

- Fix Wagmi return sepolia is supported.

fix: sepolia

---

apps/indexer-coordinator/README.md
apps/indexer-coordinator/package.json
apps/indexer-coordinator/scripts/start-testnet.sh
apps/indexer-coordinator/src/admin.controller.ts
apps/indexer-coordinator/src/configure/configure.module.ts
apps/indexer-coordinator/src/core/account.model.ts
apps/indexer-coordinator/src/core/account.service.ts
apps/indexer-coordinator/src/core/contract.service.ts
apps/indexer-coordinator/src/core/core.module.ts
apps/indexer-coordinator/src/core/network.service.ts
apps/indexer-coordinator/src/core/reward.service.ts
apps/indexer-coordinator/src/network/network.service.ts
apps/indexer-coordinator/src/network/network.type.ts
apps/indexer-coordinator/src/project/project.manifest.ts
apps/indexer-coordinator/src/utils/contractSDK.ts
apps/indexer-coordinator/src/yargs.ts
apps/indexer-coordinator/yarn.lock
deploy/docker-compose-testnet.yml
deploy/docker-compose.yml
docker/dev/.env.example
docker/dev/2_start.sh
docker/dev/docker-compose.yml
docker/test/docker-compose.yml

feat: cronjob to claim allocation rewards
fix: Fail to withdraw the controller assets
fix: rpc manifest new fields missing

Support allocation rewards and fix bugs

---

.github/workflows/prerelease.yml
apps/indexer-coordinator/package.json
apps/indexer-coordinator/src/data-source.ts
apps/indexer-coordinator/src/project/project.service.ts
apps/indexer-coordinator/src/project/types.ts
apps/indexer-coordinator/src/utils/load.ts
apps/indexer-coordinator/src/utils/template.yml
apps/indexer-coordinator/src/yargs.ts
deploy/docker-compose.yml

update subql docker with non-root user

enable pg ssl connection

---

Dockerfile

Optimize the build script to reduce Docker layers by merging redundant operations.

Optimize the build script
